# Generated by Django 5.0.1 on 2024-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='imges/default.jpg', null=True, upload_to='imges/'),
        ),
    ]
